# Generated by Django 5.1 on 2024-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicle_current_status_vehicle_warranty_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
