# Generated by Django 5.1 on 2024-08-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
