# Generated by Django 5.1 on 2024-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_servicerequest_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
