# Generated by Django 5.1 on 2024-08-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_servicerequest_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
